// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlYFfbpwB00LgTlxD07u2VfJPeaarIIg0',
    appId: '1:367053012510:web:b71f236a56e2dcd56e380f',
    messagingSenderId: '367053012510',
    projectId: 'pushnotifications-71222',
    authDomain: 'pushnotifications-71222.firebaseapp.com',
    storageBucket: 'pushnotifications-71222.appspot.com',
    measurementId: 'G-PTXTQ90XH4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgx5wKOGtzV_PcN3gdVN6FlWH0W4PGrko',
    appId: '1:367053012510:android:de81413e4a7946aa6e380f',
    messagingSenderId: '367053012510',
    projectId: 'pushnotifications-71222',
    storageBucket: 'pushnotifications-71222.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYD2UvK6sfgLjxeiZ8cN3867PBXEVLF6U',
    appId: '1:367053012510:ios:4b28472d7c331d3a6e380f',
    messagingSenderId: '367053012510',
    projectId: 'pushnotifications-71222',
    storageBucket: 'pushnotifications-71222.appspot.com',
    iosBundleId: 'com.example.pushNotifications',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYD2UvK6sfgLjxeiZ8cN3867PBXEVLF6U',
    appId: '1:367053012510:ios:4b28472d7c331d3a6e380f',
    messagingSenderId: '367053012510',
    projectId: 'pushnotifications-71222',
    storageBucket: 'pushnotifications-71222.appspot.com',
    iosBundleId: 'com.example.pushNotifications',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDlYFfbpwB00LgTlxD07u2VfJPeaarIIg0',
    appId: '1:367053012510:web:82bed2cff9e1f6eb6e380f',
    messagingSenderId: '367053012510',
    projectId: 'pushnotifications-71222',
    authDomain: 'pushnotifications-71222.firebaseapp.com',
    storageBucket: 'pushnotifications-71222.appspot.com',
    measurementId: 'G-5126TMVHVE',
  );
}
